Home_Work_Python-master/DJANGO_HOME/my_home/home_app/urls.py
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path('', views.get_basic, name='base'),
    path('register/', views.register, name='register'),
    path('after_register/', views.after_register, name='after_register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('page-one/', views.page_one, name='page_one'),
    path('page-second/', views.page_second, name='page'),
]

Home_Work_Python-master/DJANGO_HOME/my_home/my_home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
]

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/models.py
from django.contrib.auth.models import User
from django.db import models


class HtmlCard(models.Model):
    names = models.CharField(max_length=34)
    price = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    objects = models.Manager()

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


# class MyForm(AuthenticationForm):
#     email = forms.EmailField(label='Введите вашу почту', widget=forms.TextInput(attrs={'class': 'form-control'}))
#     username = forms.CharField(label='Имя')
#     password1 = forms.PasswordInput()
#     password2 = forms.PasswordInput()


class MyForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Подтверждение пароля',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

from .forms import MyForm, UserLoginForm
from .models import HtmlCard


def get_basic(request):
    html_card = HtmlCard.objects.all()
    context = {'html_card': html_card}
    return render(request, 'basic.html', context)


def after_register(request):
    template_name = 'register.html'
    return render(request, template_name)


def register(request):
    if request.method == 'GET':
        form = MyForm()
        return render(request, 'rrgister_after.html', {'form': form})

    else:
        form = MyForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.user = request.user
            new_user.save()
        return render(request, 'register.html')


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
        return redirect('home_app:base')
    else:
        form = UserLoginForm()
        return render(request, 'login.html', {'form': form})




def user_logout(request):
    logout(request)
    return redirect('home_app:base')





def page_one(request):
    template_name = 'page_one.html'
    return render(request, template_name)


def page_second(request):
    template_name = 'page_second.html'
    return render(request, template_name)

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/templates/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon"  type="image/x-icon" href="{% static 'images/favicon.ico' %}">
</head>
<body>
{% block content %}
<div class="fonn">
    <div class="fon-text"><a href="{% static 'вакансии.text' %}"  target="_blank">вакансии сегодня</a></div>

</div>
{% if user.is_authenticated %}
 <a href="{% url 'home_app:logout' %}">Выйти</a>
{% else %}
 <a href="{% url 'home_app:login' %}">Войти</a>
 <a href="{% url 'home_app:register' %}">Регистрация</a>
{% endif %}
{% endblock %}
</body>
</html>

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/templates/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">


{% block content %}

<h1 class="lop">Войти в систему</h1>
<div class="lop">
<h3 style="color:blue">Введите логин и пароль</h3>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
        <button type="submit" style="color:red">Войти</button>

</form>
</div>
{% endblock %}

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/templates/logout.html
{% load static %}



{% block content %}

<h2>Вы успешно вышли из системы</h2>
{% endblock %}

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/templates/page_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if user.is_authenticated %}
<h1>ЕЩЁ ОДНА СТРАНИЦА</h1>
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos facilis perferendis
quaerat rem repellat reprehenderit totam, voluptatem voluptatibus.
Aut delectus dolore dolorem enim itaque placeat quidem saepe soluta veniam vitae.
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dolores ipsa nobis obcaecati repellendus
voluptatum? Cumque deleniti laboriosam molestiae perferendis unde voluptatem?
At aut cupiditate distinctio explicabo, fugit recusandae voluptate.
{% else %}
<p>К сожалению просмотр закрыт пользователям без учётной записи.</p>
{% endif %}
</body>
</html>

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/templates/page_second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if user.is_authenticated %}

<h1>ВТОРАЯ СТРАНИЦА</h1>
{% else %}
<p>К сожалению просмотр закрыт пользователям без учётной записи.</p>
{% endif %}
</body>
</html>

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/templates/register.html
{% load static %}



{% block content %}

<h1>Приветствую вы зарегистрировались на нашем сайте!</h1>



</form>
{% endblock %}

Home_Work_Python-master/DJANGO_HOME/my_home/home_app/templates/rrgister_after.html
{% load static %}



{% block content %}

<h1>Доброй регистрации сер!</h1>

<form method="post">
    {% csrf_token %}
    {{form.as_div}}
        <button type="submit">Зарегистрировать</button>

</form>
{% endblock %}